"""rename department

Revision ID: 57bd3dae006b
Revises: 0cd1aa9a5050
Create Date: 2024-06-28 00:45:56.499867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bd3dae006b'
down_revision = '0cd1aa9a5050'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###')    # ### end Alembic commands ###
